apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: myfrontend
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 300Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-disk
