apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
  labels:
    app: frontend-nginx
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
        tier: frontend
    spec:
      containers:
      - name: frontend-nginx-container
        image: stacksimplify/kube-frontend-nginx:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 300Mi
        ports:
        - containerPort: 80
          protocol: TCP

      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                - "spot"

---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
  labels:
    app: frontend-nginx
    tier: frontend
spec:
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80 #ClusterIP service port
      targetPort: 80 #Container port
  type: LoadBalancer