apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword1234
        ports:
          - containerPort: 3306
            name: mysql
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 750m
            memory: 1Gi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
        - name: mysql-config
          configMap:
            name: usermanagment-dbcreation-script

---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
        
